# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metronome.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 26, 38);\n"
"color: white;\n"
"font-size: 30px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 691, 91))
        self.label.setStyleSheet("font-size: 70px;\n"
"background-color: rgb(166, 55, 0);\n"
"font-family: Cascadia Code;\n"
"border: 1px solid white;\n"
"border-radius: 20px;")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 280, 431, 71))
        self.textEdit.setStyleSheet("font-size: 45px;\n"
"border: 1px solid white;\n"
"font-family: Fira Code;\n"
"border-radius: 30px;\n"
"text-align: center;")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 390, 251, 51))
        self.pushButton.setStyleSheet("border: 1px solid white;\n"
"border-radius: 20px;\n"
"font-size: 40px;\n"
"background-color: rgb(202, 0, 0);\n"
"font-family: Cascadia Code;\n"
"text-align: center;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 460, 251, 51))
        self.pushButton_2.setStyleSheet("border: 1px solid white;\n"
"border-radius: 20px;\n"
"font-size: 40px;\n"
"background-color: rgb(202, 0, 0);\n"
"font-family: Cascadia Code;\n"
"text-align: center;")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "f0rk1l metronome"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Enter delay..."))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
